%% file locations
data_folder = ['..', filesep, '0-data'];
labelset_folder = [data_folder, filesep, 'labelsets'];

data_filename = [data_folder, filesep,'2-hierarchies',filesep,'bedroom_hierarchies.mat']; % the dataset generated by step1.
labelsetname = [labelset_folder, filesep, 'bedroomlabelset.mat']; % coarse-grained labels
output_folder = [data_folder, filesep, '3-offsetrep'];
output_filename = [output_folder, filesep, 'bedroom_offset.mat'];

if ~exist(output_folder,'dir')
   mkdir(output_folder);
end