% this list is to output the 3D scenes of a dataset
% each room(element) should have a 'id_list', which can ge generated by
% 'recon.m'
list = 1:20;

util;
load(labelset_filename);
addpath(genpath('../vistools'));

for j = 1:length(list)
    i=list(j);
    fprintf([num2str(i),'\n']);
    rdata = dataset{i};
    id_list = rdata.id_list;
    rdata.id_list = id_list;
    
	plotRoom3(rdata.obblist, rdata.labellist, 0);
	set(gcf,'position',[100 100 900 900])
	saveas(gcf, [output_img_folder,filesep,num2str(i),'.jpg']);
	close gcf;
    
    scene_folder = [output_obj_folder, filesep, 'scene-', num2str(i)];
    mkdir(scene_folder);
    recon3dscene( rdata, scene_folder, 7, objfolder_path);
end