RELATIONS.COOCCUR = 0;
RELATIONS.SUPPORT1 = -1; % row supports column
RELATIONS.SUPPORT2 = -2; % column supports row
RELATIONS.ATTACH = -3;
RELATIONS.SIDEBYSIDE = -4;
RELATIONS.SYMSUR_START = 10;

NODETYPES.COOCCUR = 2;
NODETYPES.SURROUND = 3;
NODETYPES.SUPPORT = 1;
NODETYPES.ROOM = 4;
NODETYPES.WALL = 5;

%% file locations
data_folder = ['..', filesep, '0-data'];
labelset_folder = [data_folder, filesep, 'labelsets'];

data_filename = [data_folder, filesep,'1-graphs',filesep,'bedroom_graph.mat']; % the dataset generated by step1.
labelsetname = [labelset_folder, filesep, 'bedroomlabelset.mat']; % coarse-grained labels
output_folder = [data_folder, filesep, '2-hierarchies'];
output_filename = [output_folder, filesep, 'bedroom_hierarchies.mat'];